name: Deploying Websites

on:
  push:
    branches:
      - main
    paths:
      - AWS/home_site/**
      - AWS/react_site/**
permissions:
      id-token: write
      contents: read      
jobs:
  websites:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: get node
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: get python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - run: |
            npm install -g aws-cdk
            pip install -r requirements.txt

      - name: set credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
       
      - run: |
            bash ${GITHUB_WORKSPACE}/.github/build.sh

